### ISSUE TITLE
Simple Fun #352: Reagent Formula

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#279]
https://www.codewars.com/kata/simple-fun-number-352-reagent-formula/train/javascript
```
function isValid(formula){
    if (formula.includes(1) && formula.includes(2)){
        return false;
    } else if (formula.includes(3) && formula.includes(4)){
    return false;
    } else if (formula.includes(5) && formula.includes(6)){
     return true;
     } else if(formula.includes(7) || formula.includes(8)) {
     return true;
     } else {
     return false;
     }
    }
```

**Comment by Deobp** [comment]
Rules:
material1 and material2 cannot be selected at the same time
material3 and material4 cannot be selected at the same time
material5 and material6 must be selected at the same time
material7 or  material8 must be selected(at least one, or both)

```
function isValid(formula){
    if (formula.includes(1) && formula.includes(2)){
        console.log(false);
    } else if (formula.includes(3) && formula.includes(4)){
    console.log(false);
    } else if (formula.includes(5) && formula.includes(6)){
     console.log(true);
//next line my mistake or mistake by author of  cata? 7 or 8 include so true, but in kata sample test its false !!
     } else if(formula.includes(7) || formula.includes(8)) {
     console.log(true);
     } else {
      console.log(false);
     }
    }
    console.log(isValid([1,3,5,7]))
```

**Comment by Deobp** [comment]
In issue doesn't says that if 5 or 6 includes in formula that must be included 6 or 5. Solved
```
function isValid(formula){
    if (formula.includes(1) && formula.includes(2)){
        return false;
    } else if (formula.includes(3) && formula.includes(4)){
      return false;
    } else if (formula.includes(5) && formula.includes(6)){
      return true;
    } else if(formula.includes(5)){
        if (formula.includes(6)){
            return true;
        } else {
            return false;
        }
    } else if(formula.includes(6)){
        if (formula.includes(5)){
            return true;
        } else {
            return false;
        }   
     } else if(formula.includes(7) || formula.includes(8)) {
       return true;
     } else {
       return false;
     }
}
```

**Comment by Deobp** [comment]
```
function isValid(formula){
    if(formula.includes(1) && formula.includes(2)) {
      return false;
    }
    else if(formula.includes(3) && formula.includes(4)) {
      return false;
    }
    else if(formula.includes(5) != formula.includes(6)) {
      return false;
    }
    else if(formula.includes(7) || formula.includes(8)) {
      return true; 
    } 
    else {
      return false;
    }
  }
```

**Comment by Deobp** [comment]
don't understand this line:
```
 else if(formula.includes(5) != formula.includes(6)) {
```

**Comment by odv** [comment]
@LaievskyiSasha We have the following formula of composition:
`
material1 and material2 cannot be selected at the same time

material3 and material4 cannot be selected at the same time

material5 and material6 must be selected at the same time

material7 or  material8 must be selected(at least one, or both)
`

Based on the formula, ` else if(formula.includes(5) != formula.includes(6)) ` is basically the inverted logic of `material5 and material6 must be selected at the same time`.

**Why do we have this inverted logic?**

If 5 is not included or 6 is not included we will have:

`true != false` or `false != true` and both will result to `true` meaning that the the 3rd line of the formula composition is not respected.

If both 5 and 6 are included, we will have:

`true != true` which will result in `false` so the return statement won't be executed and the checking continues so we can test the last composition rule.

We have to use this inverted logic in this way here because if we don't, we can't evaluate if 7 or 8(or both) are included).

If you don't check the full composition formula, you can't correctly return the output value.
